CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  terms_signed BOOLEAN NOT NULL DEFAULT 'f',
  not_resident BOOLEAN NOT NULL DEFAULT 'f',
  address VARCHAR NOT NULL,
  amount LONG INTEGER NOT NULL DEFAULT 0
)
